### ISSUE TITLE
[Compatability] doesn't work with MinersAdvantage

### ISSUE THREAD

**Issue by 0xebjc** [littlej541/path-under-gates#1]
Great mod, I like the concept, but your mod prevents the MinersAdvantage mod ability to do pathanation.  This feature allows to automate creating a path when one path block is created it can define a with and length, for example 3 blocks wide and 15 blocks long and when making one path block it will automatically create the 3x15 block path. 

links to MinersAdvantage
```
https://www.curseforge.com/minecraft/mc-mods/minersadvantage
https://github.com/DuelMonster/MinersAdvantage
```

**Comment by 0xebjc** [comment]
would recommend if you can create the same solution in this mod without replacing the default path it would be much more compatible with other mods.  Great idea for a mod.

**Comment by littlej541** [comment]
The issue actually lies with event handling. This mods `PlayerInteractEvent.RightClickBlock` gets registered before the same event in MinersAdvantage. This is because that mod sets itself to load after all other mods. As a result, the grass block is turned into a grass path block before the MinersAdvantage event fires, and that mod only acts on grass or dirt blocks.

I'll get a fix out that allows MinersAdvantage to fire properly but it won't create a path under a fence gate through "pathanation," that's on the other mods side. You still will be able to create a path by clicking on a grass block under a fence gate though, and it'll even continue with pathanation on the other side (although this seems to be a side effect of the way MinersAdvantage handles the pathanation functionality).
